// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7oyGbIe9fuF9sYGtBoywaPpvlliDBVTg',
    appId: '1:493560277371:web:5a5c0339c6c32434fef5de',
    messagingSenderId: '493560277371',
    projectId: 'agrisure-f4a82',
    authDomain: 'agrisure-f4a82.firebaseapp.com',
    storageBucket: 'agrisure-f4a82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_ggCLBairRvgo0EzN7JTlb41lnCvaOM',
    appId: '1:493560277371:android:e64d192002c486bcfef5de',
    messagingSenderId: '493560277371',
    projectId: 'agrisure-f4a82',
    storageBucket: 'agrisure-f4a82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4oBG4lqEYiJaOHqTXIQ3L1XITRIIMSo',
    appId: '1:493560277371:ios:38924494208144fdfef5de',
    messagingSenderId: '493560277371',
    projectId: 'agrisure-f4a82',
    storageBucket: 'agrisure-f4a82.firebasestorage.app',
    iosBundleId: 'com.example.agrisure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4oBG4lqEYiJaOHqTXIQ3L1XITRIIMSo',
    appId: '1:493560277371:ios:38924494208144fdfef5de',
    messagingSenderId: '493560277371',
    projectId: 'agrisure-f4a82',
    storageBucket: 'agrisure-f4a82.firebasestorage.app',
    iosBundleId: 'com.example.agrisure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7oyGbIe9fuF9sYGtBoywaPpvlliDBVTg',
    appId: '1:493560277371:web:033ae4da2c0cc983fef5de',
    messagingSenderId: '493560277371',
    projectId: 'agrisure-f4a82',
    authDomain: 'agrisure-f4a82.firebaseapp.com',
    storageBucket: 'agrisure-f4a82.firebasestorage.app',
  );
}
